### ISSUE TITLE
RBQL not working

### ISSUE THREAD

**Issue by bulak** [mechatroner/sublime_rainbow_csv#4]
Rainbow coloring of csv/tsv files works fine. However, I get this error message during loading and none of the right-click accessible items, including RBQL queries, from 'Rainbow CSV' are available:

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "sublime_rbql in /home/username/.config/sublime-text-3/Installed Packages/rainbow_csv.sublime-package", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "rbql_core.rbql in /home/username/.config/sublime-text-3/Installed Packages/rainbow_csv.sublime-package", line 52, in <module>
  File "./python3.3/codecs.py", line 896, in open
NotADirectoryError: [Errno 20] Not a directory: '/home/username/.config/sublime-text-3/Installed Packages/rainbow_csv.sublime-package/rbql_core/template.js.raw'
```
I am using ST version 3 build 3143 and rainbow_csv v0.2.0

I tried to uninstall/reinstall but didn't help. Any suggestions how to fix this issue is really appreciated. Thanks.

**Comment by mechatroner** [comment]
Thank you very much, @bukak ! I will fix this ASAP.

**Comment by mechatroner** [comment]
@bulak, I've published a fixed version. Try to update the extension using Package Control. You could also need to manually remove the old `/home/username/.config/sublime-text-3/Installed Packages/rainbow_csv.sublime-package` file if package control wouldn't do this automatically after the update. Please post an update on whether the new version works.

**Comment by bulak** [comment]
@mechatroner it works. I didn't need to do anything manually; Package Control updated automatically and the issue resolved. Right menu works, RBQL works. Thanks for your prompt reply and fix. Great package btw!
